### ISSUE TITLE
Direct chats are displayed as rooms

### ISSUE THREAD

**Issue by chagai95** [verdigado/rocketchat2matrix#1]
I saw this issue open on your repo:
https://git.verdigado.com/NB-Public/rocketchat2matrix/issues/71

I was just wondering, did you already figure out how to do that? Otherwise, I would love to try to contribute.

The m.direct account_data_type is in the 'account_data' in the db, maybe it can be manipulated directly? I remember I was involved in a project that also had to deal with this issue.

Here is also a function that might help which was part of a synapse module:
https://github.com/matrix-org/synapse-auto-accept-invite/blob/d673c6767862e0340e58f6e9947c7d90ec190201/synapse_auto_accept_invite/__init__.py#L116

Please let me know how I can contribute 😉

**Comment by HerHde** [comment]
Hey chagai,

Thank you for opening the first GH issue and offering your help!

I checked the situation a bit further; it seems to me as everyone in the `invite` array during room creation sees it under "People", but not the room creator.

If I understand correctly you propose to manipulate the Syanpse data? I would prefer to find a solution via the Matrix protocol, and as you mentioned the data type I found something in the Element network traffic:

It set the account data via [`PUT /_matrix/client/v3/user/%40huehe%3Amy.matrix.host/account_data/m.direct`](https://spec.matrix.org/v1.9/client-server-api/#put_matrixclientv3useruseridaccount_datatype). The body seems to be a full list of all direct chats:

```json
{
  "irrelevant, but @username in Element": [
    "!zbdRPAWTrDkJpFnIfq:my.matrix.host"
  ]
}
```
In this example, only the mentioned room is displayed under people.

I couldn't find the definition for the body yet, but this should make the implementation quite easy.

As for how you can contribute: Anything you want, really; from testing the setup and providing information on how to update the docs to implementing this requests or discussing the implementation ;-)

So, as this endpoint overwrites the whole `m.direct`, I wonder if it makes more sense to wait until the end and go over every user's direct chats, sending one request XOR updating it during room creation, using a `GET` and `PUT` the updated result?

**Comment by grvn-ht** [comment]
Hi @HerHde !
I also did some work on this issue:
https://github.com/grvn-ht/rocketchat2matrix/tree/fix-direct-chats
After looking at what you did I find it cleaner than my work ^^
However I think another feature could be added:
Renaming Solo room with username
What do you think about it?

**Comment by chagai95** [comment]
I took a look, it seems pretty good! cool!
Just wondering why you check if there is already an existing mapping? In what case would that happen? I thought the migration is meant for a new synapse...

**Comment by HerHde** [comment]
Hey you two, I think I can respond to both of you in one point:
I try to implement the script in a crash-resistant manner, if it is easily implementable.

I want the script to be able to continue if it got killed or something and gets restarted. For that, I try to keep as little state as possible in the `Storage` SQLite, which is basically the non-predictable mapping from Rocket.Chat IDs to Matrix IDs for rooms and messages, as well as the access tokens for users. Furthermore I only write to the storage after the entity has been handled.

As I can get the information from a specific endpoint, I want to rely on the synapse state and keep the door open to rerun the script after the Matrix instance has been used, which is not a _supported_ feature right now, but does not work _terribly_ either.
However, I just patched it, as a new user returned a uncaught 404 for the direct chat settings, which is now handled.

@grvn-ht Thank you and sorry I surprised you with my implementation :sweat_smile:

A few points about our different approaches: For the mentioned reasons I chose not to save that information in the Storage. And I generally try to keep the RC and Matrix types as close to the original as possible, so I didn't save the member count in the room. Furthermore, after some filtering I found it more reliable to get the Matrix members from Synapse, too.
Finally, I considered dropping the `mappingType` in the getters as well, but didn't spend the time to have a proper look if I use it anywhere.

**Comment by HerHde** [comment]
I just merged the branch into main. Is anyone testing the script, yet? I'd be curious about your results, as there is no test input data for an automated E2E test, yet and I'm only running it on my local machine and one server with a directly installed synapse.

**Comment by grvn-ht** [comment]
Hi, I tested it with your fix branch (i added try catch to  avoid 404 error) and i works well :) !!
I'm going to test main branch now and add support for alone chatting ;) 
Thanks for your work!

**Comment by chagai95** [comment]
I haven't tested it either, hopefully we at fairkom will get around to that soon.

**Comment by HerHde** [comment]
> I'm going to test main branch now and add support for alone chatting ;)

Sorry, I forgot to answer that point. It sounds like a good idea, but I thought this would be the default behaviour :thinking:
