### ISSUE TITLE
 error: Error during request: Request failed with status code 401 error:

### ISSUE THREAD

**Issue by Dimylka** [verdigado/rocketchat2matrix#16]
hi!
When the script gets to importing messages I get the following error

error: Error during request: Request failed with status code 401
error: Request: PUT /_matrix/client/v3/rooms/!SRupNIQBnaDpZzBlOS:matrix2.xxx.xxx/send/m.room.message/xkCGfTSpWX9EuJy5P?user_id=@user:matrix2.xxx.xxx&ts=1712736585621
error: Response: 401 {"errcode":"M_UNKNOWN_TOKEN","error":"Invalid access token passed.","soft_logout":false}

users and rooms were imported normally
I hope your help

**Comment by HerHde** [comment]
Hi @Dimylka,

sorry for the late reply. If this is still a problem, could you please provide me a few more lines of the log before the error and where the affected user is actually created?

Or is the user an admin or excluded?

**Comment by HerHde** [comment]
Closing for missing reply

**Comment by drygdryg** [comment]
Deleting `db.sqlite` and cleaning up the Matrix-synapse database may help you.

**Comment by HerHde** [comment]
So, basically redoing it? Otherwise you might end up with duplicates. There's also a `./reset.sh` script to help with that (using the dev setup)
