### ISSUE TITLE
Some emojis in message texts are not translated into Unicode representation

### ISSUE THREAD

**Issue by drygdryg** [verdigado/rocketchat2matrix#20]
Some emojis, for example `:partying_face:`, `:smiling_face_with_3_hearts:`, `:slight_smile:`, `:nerd:` etc., are not translated into Unicode presentation and remain in messages as is. [node-emoji](https://www.npmjs.com/package/node-emoji) library does not support the latest versions of Unicode emojis, because it relies on an old version of [emojilib](https://www.npmjs.com/package/emojilib).
A possible solution is to use `reactions.json` for emoji resolution here:
https://github.com/verdigado/rocketchat2matrix/blob/79081c79c9cdb942bee614fe3a639fac1e30b045/src/handlers/messages.ts#L128
```typescript
  const emojified = emoji.emojify(msg, {
    fallback(part) {
      const formatted_part = `:${part}:`
      return (reactionKeys as ReactionKeys)[formatted_part] || formatted_part
    },
  })
```

**Comment by HerHde** [comment]
Thanks, it works like a charm :partying_face:
I implemented it in b8359251d0eaea2e66a8f3ecf80c3c4afb3d63a2

As I was trying to use the same code for reactions as well, I noticed that currently the manually defined reactions take precedence. I think keeping it that way is a good idea, so I change the code you used in 7486970f559407918f10c86466df445d6e6b1855

This ticks off one todo from https://github.com/verdigado/rocketchat2matrix/issues/12#issuecomment-2209318751
