### ISSUE TITLE
Messages: underscores in the middle of words are interpreted as `<em>` and `<strong>`

### ISSUE THREAD

**Issue by drygdryg** [verdigado/rocketchat2matrix#25]
When converting text of messages from Markdown to HTML, underscores in the middle of words may be interpreted as `<em>` and `<strong>` tags, which leads to incorrect formatting.
For example, this Rocket.Chat message:
![image](https://github.com/user-attachments/assets/b9d3f52e-5931-42f8-8b1d-82d6d0fbd754)
converted to:
![image](https://github.com/user-attachments/assets/3a666ede-613c-484a-8e1a-cff2e1cf9abf)

And this Rocket.Chat message:
![image](https://github.com/user-attachments/assets/7bb7055f-4387-49ab-8501-11adcec06492)
converted to:
![image](https://github.com/user-attachments/assets/f5dec600-75ef-409c-9108-9eb8c97dfff7)

The possible solution is to pass `literalMidWordUnderscores=true` to Showdown options. Documentation: https://showdownjs.com/docs/available-options/#literalmidwordunderscores

**Comment by HerHde** [comment]
Thanks for the information and fix, implemented with ccbd352587e8f53eeda0b901f1a5c0f9a947ac22

**Comment by HerHde** [comment]
Related to #29: _"Showdown parses differently than Element (and probably also different from RocketChat)"_
