### ISSUE TITLE
Translate Discussions

### ISSUE THREAD

**Issue by HerHde** [verdigado/rocketchat2matrix#27]
Rocket.Chat has so called _discussions_, limited rooms in rooms. They are currently skipped and not migrated, but it would be worth a thought to translate them to threads.

**Comment by HerHde** [comment]
This is basically a migration from a ticket in our own Gitea to GitHub, I didn't check the real circumstances.
Thank you for letting me know they are converted, are they missing anything? And no, I don't want to bend them too much ;-)

**Comment by flying-scorpio** [comment]
In my exports it looks like discussions are given types `c` (chat) when the underlying room is public and `p` (private) when the room's private.
Then they're handled like any other room. As far as I can tell, not missing anything!

**Comment by HerHde** [comment]
Perfect, then I'll close this as completed. Thank you!
