### ISSUE TITLE
Command to create admin user not working for me

### ISSUE THREAD

**Issue by chagai95** [verdigado/rocketchat2matrix#4]
This other command did work:
```
docker exec rocketchat2matrix_synapse_1 register_new_matrix_user -u "$ADMIN_USERNAME" -p "$ADMIN_PASSWORD" -c /data/homeserver.yaml --admin http://localhost:8008
```
adapted from here:
https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/17c9c8a6ded366872a612f1511207aa1fa415a0c/roles/custom/matrix-synapse/templates/synapse/bin/register-user.j2#L14C2-L15C1

**Comment by chagai95** [comment]
> 1. what's your `docker-compose --version`

1.29.2

> * what's the failing command? The one from the README?

yep, this one:
```
docker-compose exec -it synapse register_new_matrix_user http://localhost:8008 -c /data/homeserver.yaml --admin --user $ADMIN_USERNAME --password $ADMIN_PASSWORD
```



> 3\. if so, did `docker-compose up -d` work?

that worked fine



> 4\. what's the output of the failed command?

no output at all


It's not a blocker for me so there is no urgency but I was just putting this here in case someone else also ran into the same issue

**Comment by HerHde** [comment]
I'll close this issue to keep some kind of overview on which issues I have to act. If there is a specific thing to do or new info, feel free to reopen this issue.

**Comment by chagai95** [comment]
I just ran into this again, maybe I should update the README? Does the [command in the README](https://github.com/verdigado/rocketchat2matrix/blob/003b5dee4772dcebab6a6040a9e3bccbb89c7a96/README.md?plain=1#L68) work for you?

**Comment by HerHde** [comment]
Yes, it *works for me* :-/
 How do you want to update it? It just came to my mind that this new `docker compose` module (not the extra package) could do the trick. Does `docker compose exec -it synapse register_new_matrix_user http://localhost:8008 --config /data/homeserver.yaml --admin --user $ADMIN_USERNAME --password $ADMIN_PASSWORD` work for you?

Or maybe with the explicit image `docker.io/matrixdotorg/synapse:v1.103.0@sha256:b7fde4f614b5d97952bc998281a876dfacaeee993f5e31081eeeac1c7ceb73f5`?

**Comment by chagai95** [comment]
`docker compose` does not work for me only `docker-compose` and the explicit image also did not work... Maybe we can wait to see if someone else also runs into this problem before we spend more time on it, I think @janonym1 and @MKoesters also tested the script, did you run into this problem?
