### ISSUE TITLE
What RC versions are supported?

### ISSUE THREAD

**Issue by chagai95** [verdigado/rocketchat2matrix#8]
I ran into some issues with the script with an older version, and now I'm running into more issues with a (kind of) newer version (4.8.7).

What versions of RC was this script tried on?

Is there a plan to support other versions?

**Comment by rasos** [comment]
They seem to just use exported Mongo dumps https://git.verdigado.com/NB-Public/rocketchat2matrix/issues/11 - afaik with up-to-date RC versions 6.x.

**Comment by HerHde** [comment]
Indeed we're using the dumps from **version 6**, maybe even started developing with v5, but I'm not sure. Going back in time proves a bit more difficult, as the [Rocket.Chat Docs are not versioned](https://developer.rocket.chat/reference/api/schema-definition/message) and their EOL is pretty quick. So there is **no plan to support different versions**.
